version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rtgzf6xxhquv"
s3_prefix = "sam-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rtgzf6xxhquv"
s3_prefix = "sam-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
